name: C++ CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: clang-16
            cc: clang-16
            cxx: clang++-16
          - os: ubuntu-latest
            compiler: gcc-13
            cc: gcc-13
            cxx: g++-13
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl
        build-type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Clang 16
        if: matrix.compiler == 'clang-16'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
          sudo apt-get install -y clang-16 lldb-16 lld-16

      - name: Install GCC 13
        if: matrix.compiler == 'gcc-13'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install gcc-13 g++-13

      - name: Export CC and CXX
        if: matrix.compiler != 'msvc'
        run: |
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: cmake --build build --target test
